import type { Metadata } from "next";
import { Noto_Serif } from "next/font/google";
import "./globals.css";
import NavBar from "./components/layout/NavBar";
import Footer from "./components/layout/Footer";


const noto_serif = Noto_Serif({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto_serif.className}>

          <NavBar/>
        <main>
        {children}
        </main>
      
        
          <Footer/>
          <div id="portal-root"/>
        </body>
    </html>
  );
}
